// Generated by CoffeeScript 2.3.2
(function() {
  var Round;

  Round = class Round {
    constructor() {
      this.coin = null;
      this.messages = null;
      this.crypto = null;
      this.inchan = null;
      this.outchan = null;
      this.logchan = null;
    }

    setUpMisc(coin, messages, crypto) {
      this.coin = coin;
      this.messages = messages;
      this.crypto = crypto;
    }

    setUpChannels(inchan, outchan, logchan) {
      this.inchan = inchan;
      this.outchan = outchan;
      this.logchan = logchan;
    }

  };

  module.exports = Round;

}).call(this);
